Repository opensearch-project/query-insights-dashboards, pull requests merged in 2025-01, with the labels that each got.

#76 Update the defaults for frontend
  public/components/__snapshots__/app.test.tsx.snap
  public/pages/TopNQueries/TopNQueries.test.tsx
  public/pages/TopNQueries/TopNQueries.tsx
  public/pages/Utils/Constants.ts
Labels: backport 2.x

#78 Fix all filters on the main page
  public/pages/QueryInsights/QueryInsights.tsx
Labels: backport 2.x

#82 fix cypress tests after changing the default values
  cypress/e2e/1_top_queries.cy.js
  cypress/e2e/3_configurations.cy.js
  cypress/e2e/4_group_details.cy.js
Labels: backport 2.x

#88 [2.x] Ensure constants and utils are under common
  .github/workflows/verify-binary-installation.yml
  common/constants.ts
  common/utils/DateUtils.ts
  common/utils/MetricUtils.ts
  common/utils/QueryUtils.ts
  package.json
  public/pages/Configuration/Configuration.tsx
  public/pages/QueryDetails/Components/QuerySummary.tsx
  public/pages/QueryDetails/QueryDetails.test.tsx
  public/pages/QueryDetails/QueryDetails.tsx
  public/pages/QueryGroupDetails/Components/QueryGroupAggregateSummary.tsx
  public/pages/QueryGroupDetails/QueryGroupDetails.test.tsx
  public/pages/QueryGroupDetails/QueryGroupDetails.tsx
  public/pages/QueryInsights/QueryInsights.tsx
  public/pages/TopNQueries/TopNQueries.tsx
  public/pages/Utils/Constants.ts
  server/routes/index.ts
Labels: backport 2.19

#90 2.19 release notes
  release-notes/opensearch-query-insights-dashboards.release-notes-2.19.0.0.md
Labels: backport 2.x, backport 2.19
